"""add apex inspect models

Revision ID: f5f3ffb25a76
Revises: 
Create Date: 2026-06-01 23:29:36.160199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f3ffb25a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('regulacao', sa.String(length=50), nullable=True),
    sa.Column('versao', sa.String(length=20), nullable=True),
    sa.Column('itens', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tag_identificacao', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('dados_tecnicos', sa.JSON(), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('data_instalacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('contratos_amc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.Column('valor_recorrente', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('inspecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('data_inspecao', sa.Date(), nullable=True),
    sa.Column('data_realizacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('respostas', sa.JSON(), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('art_numero', sa.String(length=50), nullable=True),
    sa.Column('art_pdf_url', sa.String(length=255), nullable=True),
    sa.Column('pdf_laudo_url', sa.String(length=255), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('contrato_amc_id', sa.Integer(), nullable=True),
    sa.Column('inspetor_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['contrato_amc_id'], ['contratos_amc.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['inspetor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates_checklist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspecoes')
    op.drop_table('contratos_amc')
    op.drop_table('ativos')
    op.drop_table('templates_checklist')
    # ### end Alembic commands ###
